name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Haskell and Stack
        run: ./setup-haskell-stack.sh

      - name: Build project
        run: make build

      - name: Run tests
        run: |
          make test
          if grep -q "Failures: 0" test-results.txt; then
            echo "Tests passed"
          else
            echo "Tests failed"
            exit 1
          fi
