name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Haskell Stack
        uses: actions/setup-haskell@v1
        with:
          ghc-version: '9.0.2'
          stack-version: 'latest'

      - name: Build project
        run: make build

      - name: Run tests
        run: |
          make test
          if grep -q "Failures: 0" test-results.txt; then
            echo "Tests passed"
          else
            echo "Tests failed"
            exit 1
          fi
