name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Haskell and Stack
      run: ./setup-haskell-stack.sh

    - name: Build project
      run: make build

    - name: Run tests
      run: |
        make test
        result=$?
        if [ $result -ne 0 ]; then
          echo "Tests failed"
          exit $result
        fi