name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Haskell and Stack
      uses: haskell/actions/setup@v1
      with:
        ghc-version: 9.2.7
        stack-version: 2.9.3

    - name: Build and test
      run: make build test
