name: Create Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release_project:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Haskell and Stack
        run: ./setup-haskell-stack.sh

      - name: Build
        run: make build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            ## GLaDOS Release Notes

            A GLaDOS executable is available for Linux!
            Thank you for using GLaDOS!
          draft: false
          prerelease: false

      - name: Upload Release Asset GLaDOS
        id: upload-release-asset-glados
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./glados
          asset_name: glados
          asset_content_type: application/octet-stream

      - name: Upload Release Asset GLaDOS-VM
        id: upload-release-asset-glados-vm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./glados-vm
          asset_name: glados-vm
          asset_content_type: application/octet-stream